src/profiles/urls.py
from django.urls import path, include

from .views import profile_detail_view, profile_list_view

urlpatterns = [
    path('', profile_list_view, name='profile_list'),
    path('<str:username>/', profile_detail_view, name='profile_detail_view')
]

src/saas_application/urls.py
from django.contrib import admin
from django.urls import path, include

from auth import views as auth_views
from subscriptions import views as subscription_views
from checkouts import urls as checkout_urls
from .views import (
    home_view,
    about_view,
    pw_protected_view,
    user_only_view,
    staff_only_view
)

urlpatterns = [
    path('', home_view, name='home_page'),
    path('accounts/', include('allauth.urls')),
    path('login/', auth_views.login_view, name='login_view'),
    path('register/', auth_views.register_view, name='register_view'),
    path('about/', about_view, name='about_page'),
    path('protected/user-only', user_only_view, name='protected_user_only'),
    path('protected/staff-only', staff_only_view, name='protected_staff_only'),
    path('protected/', pw_protected_view, name='protected'),
    path('profiles/', include('profiles.urls')),
    path('admin/', admin.site.urls),
    path('pricing/', subscription_views.subscription_price_view, name='pricing'),
    path('pricing/<str:interval>/', subscription_views.subscription_price_view, name='pricing_detail'),
    path('checkout/', include(checkout_urls))
]

src/visits/models.py
from django.db import models

# Create your models here.

class PageVisit(models.Model):
    path = models.TextField(blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)

src/profiles/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse

from django.contrib.auth import get_user_model
User = get_user_model()


@login_required
def profile_list_view(request):
    context = { 
        'object_list': User.objects.filter(is_active=True)
    }
    return render(request, 'profiles/list.html', context)


@login_required
def profile_detail_view(request, username=None, *args, **kwargs):
    user = request.user
    if user.has_perm('subscriptions.basic_ai'):
        return HttpResponse('congrats, you have the basic AI plan enabled.')
    profile_user_obj = get_object_or_404(User, username=username)
    is_me = profile_user_obj == user
    context = {
        'object': profile_user_obj,
        'instance': profile_user_obj,
        'owner': is_me
    }

    return render(request, 'profiles/details.html', context)

src/templates/profiles/details.html
{% extends 'base.html' %}

{% block content %}
    <div>{{ instance.username }}</div>
    {% if perms.auth or owner %}
        {% if perms.auth.view_user or owner%}
            <div>
                {{ instance.first_name }} - {{ instance.last_name}}
                Last Login: {{ instance.last_login }}
            </div>
        {% endif %}
    {% else %}
        <div>You are not allowed to see this.</div>
    {% endif %}

{% endblock content %}

src/templates/profiles/list.html
{% extends 'base.html' %}

{% block content %}
    <div>User permissions for the user {{ user.username }}</div>
    {% for perm in user.get_all_permissions %}
        <li>{{ perm }}</li>
    {% endfor %}

    {% if perms.visits and perms.visits.view_pagevisit %}
        <div>You have the permission to view this</div>
    {% endif %}

    <div>Users</div>
    {% for instance in object_list %}
        <li><a href="{% url 'profile_detail_view' instance.username %}">{{instance.username}}</a></li>
    {% endfor %}
{% endblock content %}